export class ApiEndpoints {
  static LOGIN = process.env.VUE_APP_API_URL + "/login"
  static USER_LIST = process.env.VUE_APP_API_URL + "/user/list"
  static CREATE_USER = process.env.VUE_APP_API_URL + "/user/create"
  static USER_DATA = process.env.VUE_APP_API_URL + "/user/update"
  static CAFE_LIST = process.env.VUE_APP_API_URL + "/cafe/list"
  static TOGGLE_CAFE = process.env.VUE_APP_API_URL + "/cafe/toggle"
  static CREATE_CAFE = process.env.VUE_APP_API_URL + "/cafe/create"
  static CAFE_DATA = process.env.VUE_APP_API_URL + "/cafe/update"
  static CAFE_COMMENTS = process.env.VUE_APP_API_URL + "/comment/cafe"
  static CREATE_COMMENT = process.env.VUE_APP_API_URL + "/comment/add"
  static VOTE = process.env.VUE_APP_API_URL + "/cafe/vote"
  static CAFE_HEADER = process.env.VUE_APP_API_URL + "/cafe/header-data"
  static VOTES_OPEN = process.env.VUE_APP_API_URL + "/cafe/open-votes"
  static VOTES_CLOSE = process.env.VUE_APP_API_URL + "/cafe/close-votes"
  static VOTES_AUTOCLOSE = process.env.VUE_APP_API_URL + "/cafe/set-auto-close-time"
  static ORDER_ADD = process.env.VUE_APP_API_URL + "/cafe/add-order"
  static ORDER_CHANGE = process.env.VUE_APP_API_URL + "/cafe/change-order"
  static ORDERS_GET = process.env.VUE_APP_API_URL + "/order/get-for-date"
}
